```{r, include = FALSE}
# Template for CMP project analysis
```

```{r setup, include=FALSE, cache = FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)
options(scipen=999) # removes sci notation
```

```{r libraries, include = FALSE}
library(tidyverse)
library(maptools)
library(rgdal)
library(leaflet)
library(knitr)
library(htmltools)
library(DT)
```

# Project `r as.character(id)`

## Project Table

```{r}
proj_info %>%
  filter(`Model ProjID` == id) %>%
  kable()
```


## Project Map

```{r}
#dir <- paste0("../cmp_proj_", id)
#for testing
dir <- "C:/projects/Honolulu/Version6/OMPORepo/scenarios/CMP_2016/cmp_proj_1"
shp <- paste0(dir, "/reports/proj_shapefile.shp")
  
# shp <- readShapeSpatial(shp, proj4string = CRS("+init=EPSG:4326"))
# shp <- readShapeSpatial(shp, proj4string = CRS("+init=EPSG:4269"))
shp <- readShapeSpatial(shp, proj4string = CRS("+init=nad83:5101"))
shp <- sp::spTransform(shp, CRS("+init=EPSG:4326"))
```

```{r}
leaflet() %>%
  addTiles() %>%
  addPolylines(data = shp)
```

## Project Impact

```{r, include = FALSE}
ec <- read_csv(paste0(ec_dir, "/reports/VMT and Speeds by FT and AT.csv")) %>%
  mutate(scenario = "ec")
proj <- read_csv(paste0(dir, "/reports/VMT and Speeds by FT and AT.csv")) %>%
  mutate(scenario = "project")
```

```{r}
tbl <- bind_rows(ec, proj) %>%
  mutate(AreaType = as.character(AreaType))

class_labels <- c(
  "Freeway",
  "Expressway",
  "Principal Arterial",
  "Minor Arterial",
  "Major Collector",
  "Minor Collector",
  "Local",
  "Ramp",
  "CC", 
  "Total"
)
```

### Overview

```{r}
tbl %>%
  group_by(scenario) %>%
  summarize(VMT = sum(VMT), VHT = sum(VHT), Delay = sum(Delay)) %>%
  gather(key = stat, value = number, -scenario) %>%
  spread(key = scenario, value = number) %>%
  mutate(
    Difference = ec - project,
    `Percent Diff` = round(Difference / ec * 100, 2),
    stat = factor(stat, levels = c("VMT", "VHT", "Delay", ordered = TRUE))
  ) %>%
  arrange(stat) %>%
  rename(Stat = stat, `Baseline / EC` = ec, Project = project) %>%
  kable(
    digits = c(0, 0, 0, 0, 2),
    format.args = list(big.mark = ",")
  )
```

### Vehicle Miles Traveled

```{r}
# custom container for the following tables
# used to specify "Area Type" colspan
imp_container = htmltools::withTags(table(
  class = 'display',
  thead(
    tr(
      th(colspan = 1, ""),
      th(colspan = 9, "Area Type")
    ),
    tr(
      lapply(c("FClass", "Most Dense", 2:7, "Least Dense", "Total"), th)
    )
  )
))
```

#### With Project
```{r}
summary_tbl <- tbl %>%
  group_by(AreaType, FClass, scenario) %>%
  summarize(VMT = sum(VMT)) %>%
  spread(key = scenario, value = VMT) %>%
  marg_2d(., "AreaType", "FClass") %>%
  mutate(
    diff = ec - project,
    pct_diff = ifelse(ec == 0, 0, diff / ec)
  ) %>%
  ungroup() %>%
  mutate(FClass = factor(
    FClass, levels = class_labels, ordered = TRUE
  )) %>%
  arrange(FClass)

summary_tbl %>%
  select(AreaType, FClass, project) %>%
  spread(key = AreaType, value = project) %>%
  datatable(
    container = imp_container, rownames = FALSE,
    extensions = "Buttons",
    options = list(
      dom = "Bt",
      buttons = c("copy", "csv", "pdf")
    )
  ) %>%
  formatCurrency(c(2:10), digits = 0, currency = "") %>%
  formatStyle("Total", fontWeight = "bold") %>%
  formatStyle(
    "FClass", target = "row",
    fontWeight = styleEqual(c("Total"), c("bold"))
  )
```

#### Percent Change from Baseline / EC
```{r}
summary_tbl %>%
  select(AreaType, FClass, pct_diff) %>%
  spread(key = AreaType, value = pct_diff) %>%
  datatable(
    container = imp_container, rownames = FALSE,
    extensions = "Buttons",
    options = list(
      dom = "Bt",
      buttons = c("copy", "csv", "pdf")
    )
  ) %>%
  formatPercentage(c(2:10), digits = 2) %>%
  formatStyle("Total", fontWeight = "bold") %>%
  formatStyle(
    "FClass", target = "row",
    fontWeight = styleEqual(c("Total"), c("bold"))
  )
```



### Vehicle Hours Traveled

#### With Project
```{r}
summary_tbl <- tbl %>%
  group_by(AreaType, FClass, scenario) %>%
  summarize(VHT = sum(VHT)) %>%
  spread(key = scenario, value = VHT) %>%
  marg_2d(., "AreaType", "FClass") %>%
  mutate(
    diff = ec - project,
    pct_diff = ifelse(ec == 0, 0, diff / ec)
  ) %>%
  ungroup() %>%
  mutate(FClass = factor(
    FClass, levels = class_labels, ordered = TRUE
  )) %>%
  arrange(FClass)

summary_tbl %>%
  select(AreaType, FClass, project) %>%
  spread(key = AreaType, value = project) %>%
  datatable(
    container = imp_container, rownames = FALSE,
    extensions = "Buttons",
    options = list(
      dom = "Bt",
      buttons = c("copy", "csv", "pdf")
    )
  ) %>%
  formatCurrency(c(2:10), digits = 0, currency = "") %>%
  formatStyle("Total", fontWeight = "bold") %>%
  formatStyle(
    "FClass", target = "row",
    fontWeight = styleEqual(c("Total"), c("bold"))
  )
```


#### Percent Change from Baseline / EC
```{r}
summary_tbl %>%
  select(AreaType, FClass, pct_diff) %>%
  spread(key = AreaType, value = pct_diff) %>%
  datatable(
    container = imp_container, rownames = FALSE,
    extensions = "Buttons",
    options = list(
      dom = "Bt",
      buttons = c("copy", "csv", "pdf")
    )
  ) %>%
  formatPercentage(c(2:10), digits = 2) %>%
  formatStyle("Total", fontWeight = "bold") %>%
  formatStyle(
    "FClass", target = "row",
    fontWeight = styleEqual(c("Total"), c("bold"))
  )
```


### Delay

#### With Project
```{r}
summary_tbl <- tbl %>%
  group_by(AreaType, FClass, scenario) %>%
  summarize(Delay = sum(Delay)) %>%
  spread(key = scenario, value = Delay) %>%
  marg_2d(., "AreaType", "FClass") %>%
  mutate(
    diff = ec - project,
    pct_diff = ifelse(ec == 0, 0, diff / ec)
  ) %>%
  ungroup() %>%
  mutate(FClass = factor(
    FClass, levels = class_labels, ordered = TRUE
  )) %>%
  arrange(FClass)

summary_tbl %>%
  select(AreaType, FClass, project) %>%
  spread(key = AreaType, value = project) %>%
  datatable(
    container = imp_container, rownames = FALSE,
    extensions = "Buttons",
    options = list(
      dom = "Bt",
      buttons = c("copy", "csv", "pdf")
    )
  ) %>%
  formatCurrency(c(2:10), digits = 0, currency = "") %>%
  formatStyle("Total", fontWeight = "bold") %>%
  formatStyle(
    "FClass", target = "row",
    fontWeight = styleEqual(c("Total"), c("bold"))
  )
```

#### Percent Change from Baseline / EC
```{r}
summary_tbl %>%
  select(AreaType, FClass, pct_diff) %>%
  spread(key = AreaType, value = pct_diff) %>%
  datatable(
    container = imp_container, rownames = FALSE,
    extensions = "Buttons",
    options = list(
      dom = "Bt",
      buttons = c("copy", "csv", "pdf")
    )
  ) %>%
  formatPercentage(c(2:10), digits = 2) %>%
  formatStyle("Total", fontWeight = "bold") %>%
  formatStyle(
    "FClass", target = "row",
    fontWeight = styleEqual(c("Total"), c("bold"))
  )
```